<a href="https://colab.research.google.com/github/BlackPeppercorn/Code-Challenge/blob/master/Homework3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 3


*   Singular Value Decomposition
*   Low-rank matrix approximations
*   Principal component analysis



In [2]:
import numpy as np

A = np.random.rand(4, 4)

U, Sigma, VT = np.linalg.svd(A)

print("U matrix:\n", U)

print("Sigma values:\n", Sigma)

print("VT matrix:\n", VT)

A_reconstructed = U @ np.diag(Sigma) @ VT
print("Reconstructed A:\n", A_reconstructed)

U matrix:
 [[-0.57701076  0.2607808   0.41636556  0.65245051]
 [-0.41286194  0.17531299  0.48967242 -0.74768395]
 [-0.58927166  0.22646976 -0.76572921 -0.12300057]
 [-0.38647447 -0.92193827  0.02279065  0.01216128]]
Sigma values:
 [1.79151045 0.92984842 0.48349722 0.26013451]
VT matrix:
 [[-0.52581099 -0.48648385 -0.60834681 -0.3417169 ]
 [ 0.3589739   0.35457315 -0.11302045 -0.85594509]
 [-0.72049273  0.68697498  0.08993054 -0.02946356]
 [ 0.27486501  0.40703406 -0.7804185   0.38693599]]
Reconstructed A:
 [[0.53219603 0.79624756 0.48710242 0.20542595]
 [0.22339095 0.50110409 0.60461927 0.03098414]
 [0.88863688 0.32088018 0.61009928 0.17902632]
 [0.04925266 0.04172352 0.51661322 0.97126493]]


Explanation:

Matrix Creation: A = np.random.rand(4, 4) creates a random 4x4 matrix
A with values drawn from a uniform distribution over [0, 1].

SVD Decomposition: U, Sigma, VT = np.linalg.svd(A) performs Singular Value Decomposition on
A. SVD decomposes
A into three matrices:

U: A 4x4 unitary matrix (columns are orthonormal vectors).

Σ: A 1D array of singular values (not a matrix yet).

VT: A 3x3 unitary matrix (rows are orthonormal vectors).

Printing Components:

print("U matrix:\n", U) prints the U matrix.
print("Sigma values:\n", Sigma) prints the singular values as a 1D array.

print("VT matrix:\n", VT) prints the VT matrix.

Reconstructing the Original Matrix:

A_reconstructed = U @ np.diag(Sigma) @ VT reconstructs the original matrix
A by multiplying the matrices U, Σ (converted to a diagonal matrix using np.diag(Sigma)), and VT. The reconstructed matrix should be close to the original matrix A, which is then printed.

In [3]:
k = 2

U_k = U[:, :k]
Sigma_k = np.diag(Sigma[:k])
VT_k = VT[:k, :]

A_approx = U_k @ Sigma_k @ VT_k
print("Low-rank approximation of A:\n", A_approx)

Low-rank approximation of A:
 [[0.63058813 0.58886772 0.60145481 0.14568464]
 [0.4474322  0.41762663 0.4315376  0.11321823]
 [0.63068511 0.58824126 0.61842327 0.18049876]
 [0.05632237 0.03286591 0.51809116 0.97036549]]


Explanation:

Selecting Rank k:

k = 2 specifies the rank of the approximation, meaning that only the first 2 singular values will be used in the approximation.

Truncating
U, Σ, and VT:

U_k = U[:, :k] selects the first k columns of U (4x2 matrix).

Sigma_k = np.diag(Sigma[:k]) creates a diagonal matrix using the first k singular values (2x2 matrix).

VT_k = VT[:k, :] selects the first k rows of VT (2x3 matrix).

Low-Rank Approximation:

A_approx = U_k @ Sigma_k @ VT_k multiplies the truncated matrices to approximate the original matrix A. This matrix is a "low-rank" approximation, which is close to the original matrix but with reduced complexity. It’s printed as A_approx.

In [4]:
from sklearn.decomposition import PCA

data = np.array([[2.5, 2.4, 3.5],
                 [0.5, 0.7, 1.0],
                 [2.2, 2.9, 3.2],
                 [1.9, 2.2, 2.9],
                 [3.1, 3.0, 3.8]])

pca = PCA(n_components=2)
data_reduced = pca.fit_transform(data)

print("Original Data:\n", data)
print("Reduced Data after PCA:\n", data_reduced)

print("Explained variance by each component:\n", pca.explained_variance_ratio_)

Original Data:
 [[2.5 2.4 3.5]
 [0.5 0.7 1. ]
 [2.2 2.9 3.2]
 [1.9 2.2 2.9]
 [3.1 3.  3.8]]
Reduced Data after PCA:
 [[-0.73865359 -0.24862969]
 [ 2.8759363  -0.04734653]
 [-0.64179181  0.38947837]
 [ 0.08647016  0.03270237]
 [-1.58196105 -0.12620452]]
Explained variance by each component:
 [0.97561447 0.01934415]


Explanation:

Dataset Creation: data = np.array([[...]]) creates a 5x3 matrix where each row represents a sample with 3 features. This simulates a small dataset.

Applying PCA: pca = PCA(n_components=2) initializes the PCA object to reduce the dataset to 2 dimensions (principal components).

data_reduced = pca.fit_transform(data) fits the PCA model to the data and transforms the original data to the reduced 2D space. The transformed data is stored in data_reduced.

Printing Data:

print("Original Data:\n", data) prints the original dataset.

print("Reduced Data after PCA:\n", data_reduced) prints the dataset after PCA transformation, which now has 2 dimensions instead of 3.

Explained Variance:

print("Explained variance by each component:\n", pca.explained_variance_ratio_) prints the proportion of variance explained by each of the selected principal components. This tells you how much of the original data's variance is captured by the new components.