<a href="https://colab.research.google.com/github/BlackPeppercorn/Code-Challenge/blob/master/Homework1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 1:

## Main topics:


*   Orthonormailty
*   Gram-schmidt Process
*   Eigenvalues
*   Eigenvectors


In [1]:
import numpy as np

The following code checks if vectors are ornthonormal and if they are not, the gram-schmidt process is applied to normalize the vectors

In [2]:
def is_orthonormal(vectors):
    for i in range(len(vectors)):
        for j in range(i, len(vectors)):
            dot_product = np.dot(vectors[i], vectors[j])
            if i == j:
                if not np.isclose(dot_product, 1):
                    return False
            else:
                if not np.isclose(dot_product, 0):
                    return False
    return True

In [4]:
def gram_schmidt(vectors):
    orthonormal_vectors = []
    for v in vectors:
        w = v - sum(np.dot(v, u) * u for u in orthonormal_vectors)
        w = w / np.linalg.norm(w)
        orthonormal_vectors.append(w)
    return orthonormal_vectors

In [5]:
vectors = np.array([[1, 1, 0], [1, 0, 1], [0, 1, 1]])

if is_orthonormal(vectors):
    print("The vectors are already orthonormal.")
else:
    print("The vectors are not orthonormal. Proceeding to orthonormalize them using Gram-Schmidt process...")

    orthonormal_vectors = gram_schmidt(vectors)

    print("Orthonormal vectors:")
    for vec in orthonormal_vectors:
        print(vec)

    if is_orthonormal(orthonormal_vectors):
        print("The vectors are now orthonormal.")
    else:
        print("There was an error in orthonormalizing the vectors.")

The vectors are not orthonormal. Proceeding to orthonormalize them using Gram-Schmidt process...
Orthonormal vectors:
[0.70710678 0.70710678 0.        ]
[ 0.40824829 -0.40824829  0.81649658]
[-0.57735027  0.57735027  0.57735027]
The vectors are now orthonormal.


The following code finds the eigenvalues and corresponding eigenvectors of a matrix

In [6]:
import numpy as np

A = np.array([[4, -2],
              [1,  1]])

eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:")
print(eigenvalues)

print("\nEigenvectors:")
print(eigenvectors)

print("\nVerification of the eigenvalue equation A * v = λ * v:")
for i in range(len(eigenvalues)):
    v = eigenvectors[:, i]

    Av = np.dot(A, v)

    lambda_v = eigenvalues[i] * v

    print(f"\nEigenvalue {i+1}: λ = {eigenvalues[i]}")
    print(f"A * v = {Av}")
    print(f"λ * v = {lambda_v}")

    if np.allclose(Av, lambda_v):
        print("The equation A * v = λ * v is satisfied.")
    else:
        print("The equation A * v = λ * v is NOT satisfied.")



Eigenvalues:
[3. 2.]

Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]

Verification of the eigenvalue equation A * v = λ * v:

Eigenvalue 1: λ = 3.0
A * v = [2.68328157 1.34164079]
λ * v = [2.68328157 1.34164079]
The equation A * v = λ * v is satisfied.

Eigenvalue 2: λ = 2.0
A * v = [1.41421356 1.41421356]
λ * v = [1.41421356 1.41421356]
The equation A * v = λ * v is satisfied.
